sudo: required
language: generic

services:
  - docker
before_install: 
  - docker build -t dockerized-react-app -f Dockerfile.dev .

script: 
  - docker run -e CI=true dockerized-react-app npm run test